.insuranceCompany, .adjuster, .insuranceCompany_saved, .adjuster_saved { display: none; }
.hideText { color: white; }
.columns > div { clear: none !important; float: left !important; width: 45%; margin: 0 20px; }
.columns2 > div { clear: none !important; float: left !important; width: 81%; margin: 0 20px; }
 div.pbBody div { clear: both; float: none; }
.bPageBlock .columns .detailList .labelCol { width: 33%; }
.bPageBlock .columns .detailList .data2Col { width: 66%; }
.clear { clear: both; }

